name: Java CI with Maven              # You can choose any descriptive name. 
                                      # "Java CI with Maven" is conventional.

# Only trigger on pushes (and optionally PRs) to master.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  java-test:                         # A single job that builds and tests your code
    runs-on: ubuntu-latest           # Use the latest Ubuntu runner

    steps:
      - name: Check out repository    # Step 1: checkout your code
        uses: actions/checkout@v4

      - name: Set up Java 21          # Step 2: install JDK 21 (matches your pom.xml)
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'       # AdoptOpenJDK (Temurin) distribution
          java-version: '21'          # Match this to your <maven.compiler.release>21</maven.compiler.release>

      - name: Cache Maven dependencies # Step 3 (optional but recommended)
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and run tests      # Step 4: run Maven’s test goal
        run: mvn --batch-mode --update-snapshots test

# Remove or repurpose this job unless you specifically need another shell command.
# If you don’t need it, feel free to delete “another-job” entirely.
# 
# another-job:
#   runs-on: ubuntu-latest
#   steps:
#     - name: Check out repository code
#       run: ls -la
